"""empty message

Revision ID: 000d9d34b127
Revises: ba778ef9c615
Create Date: 2021-06-21 13:03:30.276105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000d9d34b127'
down_revision = 'ba778ef9c615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_status', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('assigner_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('unassigned_date', sa.DateTime(), nullable=True),
    sa.Column('assignment_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name='fk_assignees'),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], name='fk_assigners'),
    sa.ForeignKeyConstraint(['assignment_history_id'], ['task_history.id'], name='fk_assignment_history'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id', 'project_id'], ['tasks.id', 'tasks.project_id'], name='fk_tasks'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assigned_by_status_composite', 'task_assignment_history', ['assignee_id', 'is_closed'], unique=False)
    op.create_index('idx_task_assigned_to_status_composite', 'task_assignment_history', ['assigner_id', 'is_closed'], unique=False)
    op.create_index('idx_task_assignment_history_composite', 'task_assignment_history', ['task_id', 'project_id'], unique=False)
    op.add_column('projects', sa.Column('enforce_task_assignment', sa.Boolean(), nullable=True))
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['invalidator_id', 'is_closed'], unique=False)
    op.add_column('tasks', sa.Column('assigned_to', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_users_assigned_to', 'tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_assigned_to', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['mapper_id', 'is_closed'], unique=False)
    op.drop_column('projects', 'enforce_task_assignment')
    op.drop_index('idx_task_assignment_history_composite', table_name='task_assignment_history')
    op.drop_index('idx_task_assigned_to_status_composite', table_name='task_assignment_history')
    op.drop_index('idx_task_assigned_by_status_composite', table_name='task_assignment_history')
    op.drop_table('task_assignment_history')
    # ### end Alembic commands ###
