"""empty message

Revision ID: 0bdcdc0ffd6f
Revises: 703fc561ccc6
Create Date: 2021-02-16 12:35:13.983017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdcdc0ffd6f'
down_revision = '703fc561ccc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osmcha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('changeset_id', sa.BigInteger(), nullable=True),
    sa.Column('taskhistory_id', sa.BigInteger(), nullable=True),
    sa.Column('no_of_flags', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osmcha_project_id'), 'osmcha', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_osmcha_project_id'), table_name='osmcha')
    op.drop_table('osmcha')
    # ### end Alembic commands ###
