"""empty message

Revision ID: 215392b11b0e
Revises:3ee58dee57c9
Create Date: 2019-03-20 17:11:43.674304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '215392b11b0e'
down_revision = '3ee58dee57c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mapping_editors', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('projects', sa.Column('validation_editors', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_projects_mapping_editors'), 'projects', ['mapping_editors'], unique=False)
    op.create_index(op.f('ix_projects_validation_editors'), 'projects', ['validation_editors'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_validation_editors'), table_name='projects')
    op.drop_index(op.f('ix_projects_mapping_editors'), table_name='projects')
    op.alter_column('projects', 'task_creation_mode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('projects', 'validation_editors')
    op.drop_column('projects', 'mapping_editors')
    # ### end Alembic commands ###
