"""empty message

Revision ID: 7aba630f4265
Revises: 8a6419f289aa
Create Date: 2022-08-08 12:54:31.656978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aba630f4265'
down_revision = '8a6419f289aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('earliest_street_imagery', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('image_capture_mode', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('mapillary_organization_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'mapillary_organization_id')
    op.drop_column('projects', 'image_capture_mode')
    op.drop_column('projects', 'earliest_street_imagery')
    # ### end Alembic commands ###
