"""empty message

Revision ID: 8f51fb7f4e40
Revises: d77ee40254f1
Create Date: 2019-05-01 16:09:21.471928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f51fb7f4e40'
down_revision = 'd77ee40254f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('osmcha_filter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'osmcha_filter_id')
    # ### end Alembic commands ###
