"""empty message

Revision ID: a8a7537985c0
Revises: 0a6b82b55983
Create Date: 2019-04-23 19:45:43.492558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a7537985c0'
down_revision = '0a6b82b55983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('allow_non_beginners', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'allow_non_beginners')
    # ### end Alembic commands ###
