"""empty message

Revision ID: e03826800ba9
Revises: b805df721885
Create Date: 2022-07-06 22:22:15.065202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03826800ba9'
down_revision = 'b805df721885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('imageCaptureMode', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('mapillaryOrganizationId', sa.String(), nullable=True))
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['mapper_id', 'is_closed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_validation_mapper_status_composite', table_name='task_invalidation_history')
    op.create_index('idx_task_validation_mapper_status_composite', 'task_invalidation_history', ['invalidator_id', 'is_closed'], unique=False)
    op.drop_column('projects', 'mapillaryOrganizationId')
    op.drop_column('projects', 'imageCaptureMode')
    # ### end Alembic commands ###
