"""empty message

Revision ID: f140f094bc24
Revises: 0bdcdc0ffd6f
Create Date: 2021-02-19 15:59:10.724612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f140f094bc24'
down_revision = '0bdcdc0ffd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osmcha', sa.Column('changeset_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osmcha', 'changeset_id')
    # ### end Alembic commands ###
